[package]
name = "tipup"
version = "0.1.0"
authors = ["Dan Rammer <hamersaw@bushpath.com>"]

[dependencies]
bson = "0.3"
clap = {version = "2.19", features = ["yaml"]}
env_logger = "0.3"
log = "0.3"
mongodb = "0.1"
time = "0.1"
