[package]
name = "tipup"
version = "0.1.0"
authors = ["Dan Rammer <hamersaw@bushpath.com>"]

[dependencies]
bson = "0.3"
clap = {version = "2.19", features = ["yaml"]}
chrono = "0.3"
env_logger = "0.3"
log = "0.3"
mongodb = { version = "0.2", features = ["ssl"]}
time = "0.1"
